### ISSUE TITLE
Sign Up Form

### ISSUE THREAD

**Issue by Laksheya** [Laksheya/hostelbuddy#5]
- [x] Add sign up form ( a dialogue box, use material tailwind to use dialogue box)
- [x] The fields for input are:- batchYear(text field), hostel(dropdown menu), phone(text field), whatsApp(text field), room(text field). Don't worry about rest of the fields they will extracted from google oauth.

_Reference to material tailwind [Material_ Tailwind](https://www.material-tailwind.com/docs/react/accordion)
**!! Remeber to update your branch with main**

**Comment by 1-aditya-2** [comment]
done
